### ISSUE TITLE
Improve the functionality of the interactive shell such that it has many of the features of a typical shell

### ISSUE THREAD

**Issue by jaredririe** [tylerchr/parallel-database#9]
https://github.com/carmark/pseudo-terminal-go

Features
- Up arrow
- ctrl-c to delete current line
- history

**Comment by jaredririe** [comment]
This issue is completed, although I'm not sure on one thing: if I changed code in the pseudo terminal Github repo, what is the best practice for getting these changes to both of you? Should I move the code into this repository?

**Comment by tylerchr** [comment]
You could do that, or you could fork the GitHub repo and change the
dependency to your version. Conveniently that's also the first step of
opening a merge request to the original project.

**Comment by jaredririe** [comment]
Thanks. I forked the repo and made the dependency change. The history command does not remove duplicates or allow previous commands to be re-run using !, but I think this should be sufficient.
